#include <stdio.h>
#include <math.h>

int main()
{
    int a, plus, minus, divide, square, square_2;
    int b, plus_plus, minus_minus;
    int f, plus_plus_plus, minus_minus_minus, divide_divide_divide;
    float d, adition, subtraction, divide1, indicies_1, indicies_2, divide_divide;
    float i, adition_adition, subtraction_subtraction, divide2;
    float j, adition_adition_adition, subtraction_subtraction_subtraction, divide3;
    printf("MULTIPLICATION OF NUMBERS\n\n");
    printf("PUT THE FIRST INTEGER NUMBER");
    scanf("%d", &a);
    printf("PUT THE SECOND INTEGER NUMBER");
    scanf("%d", &b);
    printf("PUT THE THIRD INTEGER NUMBER");
    scanf("%d", &f);
    printf("THE MULTIPLICATION OF THREE NUMBER IS %d\n", a * b * f);
    printf("NOW IT'S TIME TO MULTIPLY FLOAT NUMBER SO PUT A FLOAT NUMBER");
    scanf("%f", &d);
    printf("NOW PUT THE SECOND FLOAT NUMBER");
    scanf("%f", &i);
    printf("NOW PUT THE THIRD FLOAT NUMBER");
    scanf("%f", &j);
    printf("NOW THE MULTIPLICATION OF THREE FLOAT NUMBER IS %f\n", d * i * j);
    printf("NOW IT'S TIME TO DO SOME ADITION\n");
    printf("GIVE THE 1ST NUMBER");
    scanf("%d", &plus);
    printf("NOW GIVE THE SECOND NUMBER");
    scanf("%d", &plus_plus);
    printf("NOW GIVE THE THIRD NUMBER");
    scanf("%d", &plus_plus_plus);
    printf("THE ADDITION OF THREE NUMBER IS %d\n", plus + plus_plus + plus_plus_plus);
    printf("NOW IT'S TIME TO DO ADITION OF FLOAT NUMBER'S\n");
    printf("GIVE THE FIRST FLOAT NUMBER TO DO ADITION");
    scanf("%f", &adition);
    printf("NOW GIVE THE SECOND FLOAT NUMBER TO ADITION");
    scanf("%f", &adition_adition);
    printf("NOW GIVE THE THIRD FLOAT NUMBER TO ADITION");
    scanf("%f", &adition_adition_adition);
    printf("THE SUM OF THREE FLOAT NUMBER IS %f\n", adition + adition_adition + adition_adition_adition);
    printf("NOW IT'S TIME TO DO SOME SUBTRACTION\n");
    printf("GIVE A INTEGER NUMBER");
    scanf("%d", &minus);
    printf("GIVE A SECOND INTEGER NUMBER");
    scanf("%d", &minus_minus);
    printf("GIVE A THIRD INTEGER NUMBER");
    scanf("%d", &minus_minus_minus);
    printf("THE SUBTRACTION OF THREE INTEGER NUMBER IS %d\n", minus - minus_minus - minus_minus_minus);
    printf("NOW IT'S TIME TO DO THE SUBTRACTION IN FLOAT NUMBER\n");
    printf("GIVE A FLOAT NUMBER");
    scanf("%f", &subtraction);
    printf("GIVE THE SECOND FLOAT NUMBER");
    scanf("%f", &subtraction_subtraction);
    printf("GIVE A THIRD FLOAT NUMBER");
    scanf("%f", &subtraction_subtraction_subtraction);
    printf("SO THE SUBTRACTION OF THREE NUMBER IS %f\n", subtraction - subtraction_subtraction - subtraction_subtraction_subtraction);
    printf("NOW THE LAST SUM IS TO DIVIDE SOME VALUE'S\n");
    printf("GIVE THE FIRST INTEGER NUMBER TO DIVIDE");
    scanf("%d", &divide);
    printf("NOW GIVE THE SECOND INTEGER NUMBER TO DIVIDE");
    scanf("%f", &divide_divide);
    printf("NOW GIVE THE THIRD INTEGER NUMBER TO DIVIDE");
    scanf("%d", &divide_divide_divide);
    printf("THE DIVITION VALUE OF THREE INTEGER NUMBER IS %f\n", divide / divide_divide / divide_divide_divide);
    printf("NOW IT'S TIME TO DO THE SAME IN FLOAT NUMBER\n");
    printf("SO GIVE A FLOAT NUMBER TO DIVIDE");
    scanf("%f", &divide1);
    printf("NOW GIVE THE SECOND FLOAT NUMBER");
    scanf("%f", &divide2);
    printf("NOW GIVE THE THIRD FLOAT NUMBER");
    scanf("%f", &divide3);
    printf("SO THE TOTAL DIVISION OF FLOAT NUMBER IS %f\n", divide1 / divide2 / divide3);
    printf("GIVE THE NUMBER YOU WANT TO MAKE INDICIES\n");
    scanf("%d", &square);
    printf("NOW GIVE THE NUMBER HOW MANY TIME'S YOU WANT TO MAKE INDICIES WITH THE NUMBER\n");
    scanf("%d", &square_2);
    printf("INDICIES VALUE%f\n", pow(square, square_2));
    printf("NOW IT'S TIME TO DO INDICIES WITH THE FLOAT NUMBER\n");
    printf("GIVE THE NUMBER YOU WANT TO MAKE INDICIES(FLOAT)");
    scanf("%f", &indicies_1);
    printf("NOW GIVE THE NUMBER HOW MANY TIME'S YOU WANT TO MAKE INDICIES WITH THE NUMBER(FLOAT)\n");
    scanf("%f", &indicies_2);
    printf("INDICIES VALUE%f\n", pow(indicies_1, indicies_2));
}
